# Configuration Fly.io pour Blunof (Vite)
app = "blunof-telegram-miniapp"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile.fly"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
