# Configuration Fly.io pour Blunof Telegram Mini-App (Vite)
app = "blunof-telegram-miniapp"
primary_region = "cdg" # Paris, France

[build]
  dockerfile = "Dockerfile.fly"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[metrics]
  port = 9091
  path = "/metrics"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  strategy = "rolling"
  wait_timeout = "10m"

# Configuration spécifique pour Vite
[build.args]
  NODE_ENV = "production"
